image: node:8

cache:
  paths:
  - node_modules/

stages:
  - test
  - deploy

test:
  stage: test
  script:
   - npm install
   - npm test
  tags:
    - docker

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - git remote add deploy $SERVER_USERNAME@$SERVER_HOST:$SERVER_NAME
    - git push deploy master
  tags:
    - docker
